# Generated by Django 3.0.8 on 2020-12-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_auto_20200727_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='anulate',
            field=models.BooleanField(null=True, verbose_name='Anulado'),
        ),
    ]
