# Generated by Django 3.0.8 on 2020-07-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='empleados',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('3', 'ABOGADO'), ('3', 'OTRO')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
