# Generated by Django 3.0.8 on 2020-07-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_auto_20200727_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='habilidades',
            field=models.ManyToManyField(to='empleados.Habilidades'),
        ),
    ]
