# Generated by Django 3.0.8 on 2020-07-28 01:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_auto_20200727_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
    ]
