# Generated by Django 3.0.8 on 2020-08-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_empleados_hoja_vida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='hoja_vida',
        ),
    ]
