# Generated by Django 3.0.8 on 2020-08-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_remove_empleados_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombres Completos'),
        ),
    ]
